import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kun-Marketing",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return <html lang="en"></html>;
}
